export const CsvHeaders = [
  {
    label: "Serial No.",
    key: "sNo",
  },
  {
    label: "Name",
    key: "firstName",
  },
  {
    label: "Email",
    key: "email",
  },
  {
    label: "Department",
    key: "departmentTitle",
  },
  {
    label: "User Type",
    key: "userTypeTitle",
  },
  {
    label: "Organization",
    key: "OrganizationName",
  },
];
export const Columns = [
  {
    title: "Name",
    dataIndex: "firstName",
    key: "firstName",
    sorter: (a, b) =>
      a?.firstName?.toLowerCase()?.localeCompare(b.firstName?.toLowerCase()),
  },
  {
    title: "Email",
    dataIndex: "email",
    key: "email",
    sorter: (a, b) => a?.email?.toLowerCase() === b?.email?.toLowerCase(),
  },
  {
    title: "Department",
    dataIndex: "departmentTitle",
    key: "departmentTitle",
    sorter: (a, b) =>
      a?.departmentTitle
        ?.toLowerCase()
        ?.localeCompare(b.departmentTitle?.toLowerCase()),
  },
  {
    title: "User Type",
    dataIndex: "userTypeTitle",
    key: "userTypeTitle",
    sorter: (a, b) =>
      a?.userTypeTitle
        ?.toLowerCase()
        ?.localeCompare(b?.userTypeTitle?.toLowerCase()),
  },
  {
    title: "Organization",
    dataIndex: "OrganizationName",
    sorter: (a, b) =>
      a?.OrganizationName?.toLowerCase()?.localeCompare(
        b.OrganizationName?.toLowerCase()
      ),
    key: "OrganizationName",
  },
];
export const FormData = {
  submit_url: "/api/user/create",
  form: [
    {
      id: "1",
      fieldType: "text",
      isRequired: true,
      isUpdate: true,
      label: "First Name",
      name: "firstName",
      placeHolder: "Enter First Name",
      value: "",
      errorMessage: "Enter Valid First Name !",
      regex: "^[a-zA-z]+([\\s][a-zA-Z]+)*$",
    },
    {
      id: "2",
      fieldType: "text",
      isRequired: true,
      isUpdate: true,
      name: "Last Name",
      label: "Last Name",
      xmlName: "lastName",
      popupText: "",
      helpNote: "",
      placeHolder: "Enter Last Name",
      errorMessage: "Enter valid Last Name",
      regex: "^[a-zA-z]+([\\s][a-zA-Z]+)*$",
      value: "",
      validators: {
        required: true,
        minLength: 10,
      },
    },
    {
      id: "3",
      fieldType: "text",
      isRequired: true,
      isUpdate: false,
      name: "Official Email",
      label: "Official Email",
      xmlName: "email",
      popupText: "",
      helpNote: "",
      placeHolder: "Enter Official Email",
      errorMessage: "Enter valid Email",
      regex: "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$",
      value: "",
      validators: {
        required: true,
        minLength: 10,
        pattern: "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$",
      },
    },
    {
      id: "4",
      fieldType: "text",
      isRequired: true,
      isUpdate: false,
      name: "Confirm Email",
      label: "Confirm Email",
      xmlName: "confirm_email",
      popupText: "",
      helpNote: "",
      placeHolder: "Enter Confirm Email",
      errorMessage: "Enter Confirm Email",
      regex: "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$",
      value: "",
      validators: {
        required: true,
        minLength: 10,
        pattern: "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$",
      },
    },
    {
      id: "5",
      fieldType: "text",
      isRequired: true,
      isUpdate: true,
      label: "CNIC Number",
      name: "CNIC Number",
      xmlName: "cnic",
      popupText: "",
      errorMessage: "Enter valid CNIC Number XXXXX-XXXXXXX-X",
      placeHolder: "Enter CNIC Number",
      helpNote: "",
      value: "",
      regex: /^[0-9]{5}-[0-9]{7}-[0-9]$/,
      validators: {
        required: true,
        minLength: 10,
        pattern: /^[0-9]{5}-[0-9]{7}-[0-9]$/,
      },
    },
    {
      id: "6",
      fieldType: "select",
      isRequired: true,
      isUpdate: true,
      label: "Organization",
      name: "Organization",
      xmlName: "orgId",
      popupText: "",
      helpNote: "",
      placeHolder: "Select Organization",
      errorMessage: "Field Required!",
      value: "",
      regex: "",
      options: [],
    },
    {
      id: "7",
      fieldType: "select",
      isRequired: true,
      isUpdate: true,
      label: "Department",
      name: "Department",
      xmlName: "deptCode",
      popupText: "",
      helpNote: "",
      placeHolder: "Select Department",
      errorMessage: "Field Required!",
      value: "",
      regex: "",
      options: [],
    },
    {
      id: "8",
      fieldType: "select",
      isRequired: true,
      isUpdate: true,
      label: "Designation",
      name: "Designation",
      xmlName: "designCode",
      popupText: "",
      helpNote: "",
      placeHolder: "Select Designation",
      errorMessage: "Field Required!",
      value: "",
      regex: "",
      options: [],
    },
    {
      id: "9",
      fieldType: "text",
      isRequired: true,
      isUpdate: true,
      label: "Landline",
      name: "Landline",
      xmlName: "contact",
      popupText: "",
      errorMessage: "Enter valid Landline 0XX-XXXXXXX",
      placeHolder: "Enter Landline",
      helpNote: "",
      value: "",
      regex: /^[0-9]{3}-[0-9]{7}$/,
      validators: {
        required: true,
        minLength: 10,
        pattern: /^[0-9]{3}-[0-9]{7}$/,
      },
    },
    // {
    //   id: "10",
    //   fieldType: "text",
    //   isRequired: true,
    //   isUpdate: true,
    //   label: "Mobile Number",
    //   name: "Mobile Number",
    //   xmlName: "mobileNumber",
    //   popupText: "",
    //   errorMessage: "Enter valid Mobile Number 03XX-XXXXXXX",
    //   placeHolder: "Enter Mobile Number",
    //   helpNote: "",
    //   value: "",
    //   regex: /^[0-9]{4}-[0-9]{7}$/,
    //   validators: {
    //     required: true,
    //     minLength: 10,
    //     pattern: /^[0-9]{4}-[0-9]{7}$/,
    //   },
    // },
    {
      id: "11",
      fieldType: "text",
      isRequired: true,
      isUpdate: true,
      label: "Address",
      name: "Address",
      xmlName: "postalAddress",
      popupText: "",
      errorMessage: "Enter valid Address",
      placeHolder: "Enter your address",
      helpNote: "",
      value: "",
      regex: "",
      validators: {
        required: true,
        minLength: 10,
        pattern: "",
      },
    },
    {
      id: "12",
      fieldType: "password",
      isRequired: true,
      isUpdate: false,
      label: "Password",
      name: "Password",
      xmlName: "password",
      popupText: "",
      errorMessage: "Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character",
      placeHolder: "Enter New Password",
      helpNote: "",
      value: "",
      regex: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.+!@#\$%\^&\*])/,
      validators: {
        required: true,
        minLength: 10,
        pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.+!@#\$%\^&\*])/,
      },
    },
    {
      id: "13",
      fieldType: "password",
      isRequired: true,
      isUpdate: false,
      label: "Confirm Password",
      name: "Confirm Password",
      xmlName: "confirm_password",
      popupText: "",
      errorMessage: "Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character",
      placeHolder: "Enter New Password",
      helpNote: "",
      value: "",
      regex: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.+!@#\$%\^&\*])/,
      validators: {
        required: true,
        minLength: 10,
        pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.+!@#\$%\^&\*])/,
      },
    },
  ],
};
